FROM python:3.11-slim

WORKDIR /service

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/service

COPY requirements.txt dev-requirements.txt pyproject.toml pytest.ini ./
RUN pip install --no-cache-dir -r requirements.txt -r dev-requirements.txt

COPY . .

ENTRYPOINT ["pytest"]
CMD ["tests"]
